[package]
name = "pdf-summarize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf-extract = "*"
reqwest = { version = "*", features = ["json", "blocking"] }
serde_json = "*"
dotenv = "*"
